version: "3" 

services:  
  textencryption:    
    container_name: textencryption
    image: dockerhub.petrmikolas.cz/textencryption:latest  
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    ports:
      - 7500:80
      - 7501:443
    network_mode: bridge 